# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Felipe del Pozo"
description: Web developer

email: felipedelpozo@dtoo.es
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Felipe del Pozo'
author: 'Felipe del Pozo'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://felipedelpozo.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/felipedelpozo
    desc: 	Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/felipedelpozo
    desc:	Github
#    share_url:
#    share_title:
#    share_link:

  - icon:	google-plus
    url:	https://google.com/+FelipedelPozo
    desc: 	Google+
#    share_url:
#    share_title:
#    share_link:

analytics_tracking_id : 'UA-64152234-1'